// Generated by dia2code
#ifndef SERVER__COMMANDE__H
#define SERVER__COMMANDE__H

#include <string>

namespace server {

  /// class Commande - 
  class Commande {
    // Attributes
  public:
    int epoch;
    std::string type;
    bool joueur;
    int ancx;
    int ancy;
    int newx;
    int newy;
    int degat;
    bool sauvEquipe;
    int sauvType;
    bool afficher;
  };

};

#endif
