// Generated by dia2code
#ifndef SERVER__COMMANDEDB__H
#define SERVER__COMMANDEDB__H

#include <vector>

namespace server {
  class Commande;
}

#include "Commande.h"

namespace server {

  /// class CommandeDB - 
  class CommandeDB {
    // Associations
    // Attributes
  private:
    std::vector<Commande> lsCommandes;
    // Operations
  public:
    CommandeDB ();
    std::vector<Commande> getCommandes (int ep);
    void addCommande (Commande cmd);
  };

};

#endif
