// Generated by dia2code
#ifndef SERVER__COMMANDESERVICE__H
#define SERVER__COMMANDESERVICE__H

#include <json/json.h>

namespace server {
  class CommandeDB;
  class AbstractService;
}

#include "HttpStatus.h"
#include "AbstractService.h"
#include "CommandeDB.h"

namespace server {

  /// class CommandeService - 
  class CommandeService : public server::AbstractService {
    // Associations
    // Attributes
  private:
    CommandeDB& cmdDB;
    // Operations
  public:
    CommandeService (CommandeDB& commandeDB);
    HttpStatus get (Json::Value& out, int epoch) const;
    HttpStatus put (Json::Value& in);
  };

};

#endif
