// Generated by dia2code
#ifndef ENGINE__ACTION__H
#define ENGINE__ACTION__H


namespace engine {

  /// class Action - 
  class Action {
    // Operations
  public:
    virtual ~Action ();
  };

};

#endif
