// Generated by dia2code
#ifndef ENGINE__CATEGORIECOMMANDE__H
#define ENGINE__CATEGORIECOMMANDE__H


namespace engine {

  enum CategorieCommande {
    deplacementCamera     = 1,
    zoomCamera     = 2,
    clicSouris     = 3,
    echap     = 4
  };

};

#endif
