// Generated by dia2code
#ifndef ENGINE__CHANGERTOUR__H
#define ENGINE__CHANGERTOUR__H


namespace state {
  class Etat;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class ChangerTour - 
  class ChangerTour : public engine::Action {
    // Attributes
  private:
    bool afficher;
    // Operations
  public:
    ChangerTour (bool afficher);
    void appliquer (state::Etat* etat);
    void annuler (state::Etat* etat);
  };

};

#endif
