// Generated by dia2code
#ifndef ENGINE__CHANGERMODE__H
#define ENGINE__CHANGERMODE__H


namespace engine {
  class Moteur;
};
namespace state {
  class Etat;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class ChangerMode - 
  class ChangerMode : public engine::Action {
    // Attributes
  private:
    /// 		
    Moteur* moteur;
  protected:
    int idMode;
    // Operations
  public:
    ChangerMode (int IdMode, Moteur* moteur);
    void appliquer (state::Etat* etat);
  };

};

#endif
