// Generated by dia2code
#ifndef ENGINE__CHANGERINIT__H
#define ENGINE__CHANGERINIT__H


namespace state {
  class Etat;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class ChangerInit - 
  class ChangerInit : public engine::Action {
    // Attributes
  private:
    int indice;
    int donnee;
    // Operations
  public:
    ChangerInit (int indice, int donnee);
    void appliquer (state::Etat* etat);
    void annuler (state::Etat* etat);
  };

};

#endif
