// Generated by dia2code
#ifndef ENGINE__CHANGERMODE__H
#define ENGINE__CHANGERMODE__H


namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class ChangerMode - 
  class ChangerMode : public engine::Action {
    // Operations
  public:
    void ChangerMode (int IdMode);
  };

};

#endif
