// Generated by dia2code
#ifndef ENGINE__COMMANDECLIC__H
#define ENGINE__COMMANDECLIC__H


namespace engine {
  class Commande;
}

#include "CategorieCommande.h"
#include "Commande.h"

namespace engine {

  /// class CommandeClic - 
  class CommandeClic : public engine::Commande {
    // Attributes
  private:
    int x;
    int y;
    // Operations
  public:
    CommandeClic (int i, int j);
    CategorieCommande getCategorie ();
    int getX ();
    int getY ();
  };

};

#endif
