// Generated by dia2code
#ifndef ENGINE__COMMANDEECHAP__H
#define ENGINE__COMMANDEECHAP__H


namespace engine {
  class Commande;
}

#include "CategorieCommande.h"
#include "Commande.h"

namespace engine {

  /// class CommandeEchap - 
  class CommandeEchap : public engine::Commande {
    // Operations
  public:
    CommandeEchap ();
    CategorieCommande getCategorie ();
  };

};

#endif
