// Generated by dia2code
#ifndef ENGINE__COMMANDEZOOMCAMERA__H
#define ENGINE__COMMANDEZOOMCAMERA__H


namespace engine {
  class Commande;
}

#include "CategorieCommande.h"
#include "Commande.h"

namespace engine {

  /// class CommandeZoomCamera - 
  class CommandeZoomCamera : public engine::Commande {
    // Attributes
  private:
    /// 		
    int i;
    // Operations
  public:
    CommandeZoomCamera (int i);
    CategorieCommande getCategorie ();
    int geti ();
  };

};

#endif
