// Generated by dia2code
#ifndef ENGINE__DEPLACEMENTCAMERA__H
#define ENGINE__DEPLACEMENTCAMERA__H


namespace state {
  class Etat;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class DeplacementCamera - 
  class DeplacementCamera : public engine::Action {
    // Operations
  public:
    void appliquer (state::Etat* etat);
  };

};

#endif
