// Generated by dia2code
#ifndef ENGINE__DEPLACEMENTCAMERA__H
#define ENGINE__DEPLACEMENTCAMERA__H


namespace state {
  class Etat;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class DeplacementCamera - 
  class DeplacementCamera : public engine::Action {
    // Attributes
  protected:
    int originex;
    int originey;
    int ciblex;
    int cibley;
    // Operations
  public:
    DeplacementCamera (int originex, int originey, int ciblex, int cibley);
    void appliquer (state::Etat* etat);
  };

};

#endif
