// Generated by dia2code
#ifndef ENGINE__DEPLACEMENTCAMERA__H
#define ENGINE__DEPLACEMENTCAMERA__H


namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class DeplacementCamera - 
  class DeplacementCamera : public engine::Action {
  };

};

#endif
