// Generated by dia2code
#ifndef ENGINE__DEPLACEMENT__H
#define ENGINE__DEPLACEMENT__H


namespace state {
  class Etat;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class Deplacement - 
  class Deplacement : public engine::Action {
    // Attributes
  private:
    int origineX;
    int origineY;
    int cibleX;
    int cibleY;
    // Operations
  public:
    Deplacement (int Originex, int Originey, int Ciblex, int Cibley);
    void appliquer (state::Etat* etat, bool afficher);
    state::CaseTerrain* getCaseArrivee (state::Etat* etat);
    void annuler (state::Etat* etat, bool afficher);
    int getDistance ();
    void printOrigine ();
    void printArrivee ();
  };

};

#endif
