// Generated by dia2code
#ifndef ENGINE__DIRECTION__H
#define ENGINE__DIRECTION__H


namespace engine {

  enum Direction {
    Nord     = 1,
    Sud     = 2,
    Est     = 3,
    Ouest     = 4
  };

};

#endif
