// Generated by dia2code
#ifndef ENGINE__DéPLACEMENT__H
#define ENGINE__DéPLACEMENT__H


namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class Déplacement - 
  class Déplacement : public engine::Action {
    // Attributes
  public:
    int Originex;
    int Originey;
    int Ciblex;
    int Cibley;
    // Operations
  public:
    void Déplacement (int Originex, int Originey, int Ciblex, int Cibley);
  };

};

#endif
