// Generated by dia2code
#ifndef ENGINE__DéPLACEMENTCAMéRA__H
#define ENGINE__DéPLACEMENTCAMéRA__H


namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class DéplacementCaméra - 
  class DéplacementCaméra : public engine::Action {
  };

};

#endif
