// Generated by dia2code
#ifndef ENGINE__LISTECOMMANDE__H
#define ENGINE__LISTECOMMANDE__H

#include <map>

namespace engine {
  class Commande;
}

#include "Commande.h"

namespace engine {

  /// class ListeCommande - 
  class ListeCommande {
    // Associations
    // Attributes
  private:
    std::map<int,Commande*> commandes;
    // Operations
  public:
    ListeCommande ();
    ~ListeCommande ();
    Commande* get (int categorie);
    void set (Commande* cmd);
    int taille ();
    void vider ();
  };

};

#endif
