// Generated by dia2code
#ifndef ENGINE__MODE__H
#define ENGINE__MODE__H


namespace engine {

  enum Mode {
    demarrer     = 1,
    initialisation     = 2,
    jeu     = 3,
    deplacement     = 4,
    attaque     = 5,
    selection     = 6,
    placement     = 7
  };

};

#endif
