// Generated by dia2code
#ifndef ENGINE__MOTEUR__H
#define ENGINE__MOTEUR__H

#include <ctime>
#include <ctime>

namespace state {
  class Etat;
};
namespace engine {
  class ListeCommande;
  class ListeActions;
  class Historique;
  class Commande;
  class Action;
  class Regulateur;
}

#include "ListeCommande.h"
#include "Mode.h"
#include "state/Etat.h"
#include "Regulateur.h"

namespace engine {

  /// class Moteur - 
  class Moteur {
    // Associations
    // Attributes
  private:
    state::Etat* etat;
    ListeCommande listeCommande;
    clock_t derniereMaj;
    Mode mode;
    float zoom;
    int camerax;
    int cameray;
    /// 	
    ListeActions* aVerifier;
    /// 	
    Historique* historique;
    bool enregistrer;
    // Operations
  public:
    Moteur (state::Etat* etat);
    ~Moteur ();
    state::Etat* getEtat ();
    void ajouterCommande (Commande* cmd);
    Mode getMode ();
    void update (clock_t t);
    void setMode (Mode mode);
    void convertirCommande (bool afficher);
    float getZoom ( );
    void setZoom (float z);
    int getCamerax ();
    void setCamerax (int cx);
    int getCameray ();
    void setCameray (int cy);
    void ajouterAction (Action* action);
    void finDuTour ();
    void annuler ();
    void commencerEnregistrement ();
    void arreterEnregistrement ();
    bool enregistrementActive ();
    void enregistrerAction (Action* action);
  };

};

#endif
