// Generated by dia2code
#ifndef ENGINE__MOTEUR__H
#define ENGINE__MOTEUR__H


namespace state {
  class Etat;
};
namespace engine {
  class ListeCommande;
  class Commande;
  class Regulateur;
}

#include "ListeCommande.h"
#include "Mode.h"
#include "state/Etat.h"
#include "Regulateur.h"

namespace engine {

  /// class Moteur - 
  class Moteur {
    // Associations
    // Attributes
  private:
    state::Etat* etat;
    ListeCommande listeCommande;
    clock_t derniereMaj;
    Mode mode;
    // Operations
  public:
    Moteur (state::Etat* etat);
    ~Moteur ();
    state::Etat* getEtat ();
    void ajouterCommande (Commande* cmd);
    Mode getMode ();
    void update (clock_t t);
    void setMode (Mode mode);
  };

};

#endif
