// Generated by dia2code
#ifndef ENGINE__MOTEUR__H
#define ENGINE__MOTEUR__H


namespace engine {
  class ListeCommande;
  class Commande;
  class Regulateur;
}

#include "ListeCommande.h"
#include "Mode.h"
#include "Regulateur.h"

namespace engine {

  /// class Moteur - 
  class Moteur {
    // Associations
    // Attributes
  private:
    Etat* etat;
    ListeCommande listeCommande;
    clock_t derniereMaj;
    Mode mode;
    // Operations
  public:
    Moteur ();
    ~Moteur ();
    Etat* getEtat ();
    void ajouterCommande (Commande* cmd);
    Mode getMode ();
    update (clock_t t);
    setMode (Mode mode);
  };

};

#endif
