// Generated by dia2code
#ifndef ENGINE__PLACEMENTTROUPE__H
#define ENGINE__PLACEMENTTROUPE__H


namespace state {
  class Etat;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class PlacementTroupe - 
  class PlacementTroupe : public engine::Action {
    // Attributes
  private:
    int x;
    int y;
    int id;
    // Operations
  public:
    PlacementTroupe (int x, int y, int id);
    void appliquer (state::Etat* etat);
  };

};

#endif
