// Generated by dia2code
#ifndef ENGINE__REGULATEUR__H
#define ENGINE__REGULATEUR__H


namespace state {
  class Etat;
};
namespace engine {
  class ListeCommande;
  class ListeActions;
  class Moteur;
}

#include "ListeActions.h"

namespace engine {

  /// class Regulateur - 
  class Regulateur {
    // Associations
    // Attributes
  protected:
    state::Etat* etatCourant;
    ListeCommande* commandes;
    ListeActions* actions;
    // Operations
  public:
    Regulateur (ListeActions* lsAction, state::Etat* etat, ListeCommande* lsCmd, Moteur* moteur);
    ~Regulateur ();
    void appliquer ();
  };

};

#endif
