// Generated by dia2code
#ifndef ENGINE__REGULATEUR__H
#define ENGINE__REGULATEUR__H


namespace engine {
  class ListeActions;
};
namespace state {
  class Etat;
};
namespace engine {
  class Moteur;
}

#include "ListeActions.h"

namespace engine {

  /// class Regulateur - 
  class Regulateur {
    // Associations
    // Attributes
  private:
    ListeActions* actions;
  protected:
    state::Etat* etatCourant;
    // Operations
  public:
    Regulateur (ListeActions* lsAction, state::Etat* etat, Moteur* moteur);
    ~Regulateur ();
    void appliquer (Moteur* moteur);
  };

};

#endif
