// Generated by dia2code
#ifndef ENGINE__SELECTION__H
#define ENGINE__SELECTION__H


namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class Selection - 
  class Selection : public engine::Action {
    // Attributes
  protected:
    int Selectionx;
    int Selectiony;
    // Operations
  public:
    Selection (int Selectionx, int Selectiony);
  };

};

#endif
