// Generated by dia2code
#ifndef ENGINE__SELECTION__H
#define ENGINE__SELECTION__H


namespace state {
  class Etat;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class Selection - 
  class Selection : public engine::Action {
    // Attributes
  private:
    state::Personnage* ancienSelect;
    /// 		
    bool afficher;
  protected:
    int selectionX;
    int selectionY;
    // Operations
  public:
    Selection (int Selectionx, int Selectiony, bool afficher);
    void appliquer (state::Etat* etat);
    void annuler (state::Etat* etat);
  };

};

#endif
