// Generated by dia2code
#ifndef ENGINE__ZOOM__H
#define ENGINE__ZOOM__H


namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class Zoom - 
  class Zoom : public engine::Action {
  };

};

#endif
