// Generated by dia2code
#ifndef ENGINE__ZOOM__H
#define ENGINE__ZOOM__H


namespace state {
  class Etat;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class Zoom - 
  class Zoom : public engine::Action {
    // Attributes
  private:
    int i;
    // Operations
  public:
    Zoom (int i);
    void appliquer (state::Etat* etat, bool afficher);
    void annuler (state::Etat* etat, bool afficher);
  };

};

#endif
