// Generated by dia2code
#ifndef RENDER__BOUTON__H
#define RENDER__BOUTON__H


namespace render {

  /// class Bouton - 
  class Bouton {
    // Attributes
  private:
    int ID;
    // Operations
  public:
    Bouton (int ID);
    void setID (int ID);
    int getID ();
  };

};

#endif
