// Generated by dia2code
#ifndef RENDER__BOUTON__H
#define RENDER__BOUTON__H


namespace render {

  /// class Bouton - 
  class Bouton {
    // Attributes
  public:
    bool Actif;
  private:
    int ID;
    // Operations
  public:
    Bouton (int ID, bool Actif);
    void setActif (bool Actif);
    bool getActif ();
    void setID (int ID);
    int getID ();
  };

};

#endif
