// Generated by dia2code
#ifndef RENDER__COUCHE__H
#define RENDER__COUCHE__H

#include <SFML/Graphics.hpp>
#include <vector>

namespace render {
  class Tuile;
};
namespace state {
  class Observateur;
}

#include "state/Observateur.h"
#include "Tuile.h"

namespace render {

  /// class Couche - 
  class Couche : public state::Observateur {
    // Associations
    // Attributes
  public:
    sf::RenderWindow* window;
  private:
    std::vector<Tuile*> tuiles;
    // Operations
  public:
    Couche (sf::RenderWindow* window);
    Tuile* getTuile (int i, int j);
    void setTuile (int i, int j, Tuile* tuile);
    void changementEtat (state::EvenementEtat& e);
    void afficher ();
    void addTuile (Tuile* tuile);
  };

};

#endif
