// Generated by dia2code
#ifndef RENDER__COUCHE__H
#define RENDER__COUCHE__H

#include <vector>

namespace render {
  class Tuile;
};
namespace state {
  class Observateur;
}

#include "state/Observateur.h"
#include "Tuile.h"

namespace render {

  /// class Couche - 
  class Couche : public state::Observateur {
    // Associations
    // Attributes
  private:
    std::vector<Tuile*> tuiles;
    // Operations
  public:
    Couche ();
    Tuile* getTuile (int i, int j);
    void setTuile (int i, int j, Tuile* tuile);
    void changementEtat (const EvenementEtat& e);
  };

};

#endif
