// Generated by dia2code
#ifndef RENDER__PANNEAU__H
#define RENDER__PANNEAU__H

#include <SFML/Graphics.hpp>

namespace render {

  /// class Panneau - 
  class Panneau {
    // Attributes
  private:
    sf::Sprite fond;
    sf::Sprite boutA;
    sf::Sprite boutD;
    sf::Texture textFond;
    sf::Texture textBoutA;
    sf::Texture textBoutD;
    // Operations
  public:
    Panneau ();
    void draw (sf::RenderWindow* window);
  };

};

#endif
