// Generated by dia2code
#ifndef RENDER__PANNEAU__H
#define RENDER__PANNEAU__H

#include <vector>
#include <SFML/Graphics.hpp>

namespace render {
  class Bouton;
};
namespace state {
  class Personnage;
  class Observateur;
}

#include "state/Personnage.h"
#include "state/Observateur.h"
#include "Bouton.h"

namespace render {

  /// class Panneau - 
  class Panneau {
    // Associations
    // Attributes
  private:
    std::vector<Bouton*> listeBoutons;
    sf::Sprite fond;
    bool estSelect;
    sf::Texture textFond;
    sf::Text nom;
    sf::Font font;
    sf::Text txtPa;
    sf::RectangleShape paTot;
    sf::RectangleShape paRest;
    sf::Text txtPv;
    sf::RectangleShape pvTot;
    sf::RectangleShape pvRest;
    std::vector<int> donneesInit;
    bool tour;
    // Operations
  public:
    Panneau ();
    void draw (sf::RenderWindow* window);
    void setSelectionne (state::Etat* etat, state::Personnage* p);
    void unsetSelectionne ();
    Bouton* getBouton (int indice);
    int getTaille ();
    int getDonneesInit (int indice);
    void setDonneesInit (int indice, int donnee);
    void changerTour ();
  };

};

#endif
