// Generated by dia2code
#ifndef RENDER__PANNEAU__H
#define RENDER__PANNEAU__H

#include <SFML/Graphics.hpp>

namespace state {
  class Personnage;
  class Observateur;
}

#include "state/Personnage.h"
#include "state/Observateur.h"

namespace render {

  /// class Panneau - 
  class Panneau {
    // Attributes
  private:
    sf::Sprite fond;
    sf::Sprite boutA;
    sf::Sprite boutD;
    sf::Texture textFond;
    sf::Texture textBoutAOff;
    sf::Texture textBoutDOff;
    bool estSelect;
    sf::Text nom;
    sf::RectangleShape paTot;
    sf::RectangleShape paRest;
    sf::Font font;
    sf::Text txtPa;
    sf::RectangleShape pvTot;
    sf::RectangleShape pvRest;
    sf::Text txtPv;
    sf::Texture textBoutAOn;
    sf::Texture textBoutDOn;
    // Operations
  public:
    Panneau ();
    void draw (sf::RenderWindow* window);
    void setSelectionne (state::Etat* etat, state::Personnage* p);
    void unsetSelectionne ();
  };

};

#endif
