// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H

#include <SFML/Graphics.hpp>

namespace render {
  class Message;
  class Couche;
  class Panneau;
};
namespace state {
  class Observateur;
}

#include "state/Observateur.h"
#include "Message.h"
#include "Panneau.h"
#include "Couche.h"

namespace render {

  /// class Scene - 
  class Scene : public state::Observateur {
    // Associations
    // Attributes
  public:
    Message* message;
  private:
    Couche* couchePersonnage;
    Couche* coucheTerrain;
    state::Etat* etat;
    sf::RenderWindow* window;
    float tx;
    float ty;
    float zoom;
    int camerax;
    int cameray;
    Panneau* panneau;
    // Operations
  public:
    Scene (state::Etat* etat, sf::RenderWindow* window);
    virtual ~Scene ();
    void changementEtat (state::EvenementEtat& e);
    void afficher ();
    int getZoom ();
    void setZoom (int z);
    void setCamera (int x, int y);
    float getCoeff ();
    int getCamerax ();
    int getCameray ();
  };

};

#endif
