// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H

#include <SFML/Graphics.hpp>

namespace render {
  class Couche;
};
namespace state {
  class Observateur;
}

#include "state/Observateur.h"
#include "Couche.h"

namespace render {

  /// class Scene - 
  class Scene : public state::Observateur {
    // Associations
    // Attributes
  private:
    Couche* couchePersonnage;
    Couche* coucheTerrain;
    state::Etat* etat;
    sf::RenderWindow* window;
    // Operations
  public:
    Scene (state::Etat* etat, sf::RenderWindow* window);
    virtual ~Scene ();
    void changementEtat (state::EvenementEtat& e);
    void afficher ();
    void jouerMusique ();
  };

};

#endif
