// Generated by dia2code
#ifndef RENDER__TUILE__H
#define RENDER__TUILE__H


namespace render {

  /// class Tuile - 
  class Tuile {
    // Attributes
  protected:
    int x;
    int y;
    int id;
    // Operations
  public:
    virtual ~Tuile ();
    virtual bool estAnime () = 0;
    int const getID ();
    int const getX ();
    int const getY ();
    void setX (int x);
    void setY (int y);
    void setID (int id);
  };

};

#endif
