// Generated by dia2code
#ifndef AI__IA__H
#define AI__IA__H


namespace state {
  class Etat;
};
namespace engine {
  class Moteur;
}

#include "state/Etat.h"

namespace AI {

  /// class IA - 
  class IA {
    // Attributes
  private:
    int i;
  protected:
    state::Etat* etat;
    bool equipe;
    /// 			
    engine::Moteur* moteur;
    // Operations
  public:
    IA (state::Etat* etat, engine::Moteur* moteur);
    ~IA ();
    bool appliquer ( bool);
    bool estFini ();
  };

};

#endif
