// Generated by dia2code
#ifndef AELEMENTALLOC__H
#define AELEMENTALLOC__H

/// class AElementAlloc - 
class AElementAlloc {
  // Operations
public:
  virtual ~AElementAlloc ();
  virtual Element* newInstance () = 0;
};

#endif
