// Generated by dia2code
#ifndef CASETERRAIN__H
#define CASETERRAIN__H

#include <vector>
#include "Element.h"
#include "Acces.h"

/// class CaseTerrain - 
class CaseTerrain : public Element{
  // Associations
  // Attributes
private:
  int id;
  std::vector<Acces> liste_acces;
  int hauteur;
  // Operations
public:
  CaseTerrain (int id);
  bool const estPersonnage ();
  int getType ();
};

#endif
