// Generated by dia2code
#ifndef STATE__CASETERRAIN__H
#define STATE__CASETERRAIN__H

#include <vector>

namespace state {
  class CaseTerrain;
  class Element;
}

#include "Acces.h"
#include "Element.h"

namespace state {

  /// class CaseTerrain - 
  class CaseTerrain : public state::Element {
    // Associations
    // Attributes
  private:
    int id;
    std::vector<Acces> liste_acces;
    int hauteur;
    // Operations
  public:
    CaseTerrain (int id = 0);
    bool const estPersonnage ();
    int const getID ();
    CaseTerrain* clone ();
    bool estAccessible (Acces acces);
  };

};

#endif
