// Generated by dia2code
#ifndef STATE__CREATIONELEMENT__H
#define STATE__CREATIONELEMENT__H


namespace state {
  class IObservateurEtat;
}

#include "IObservateurEtat.h"

namespace state {

  /// class CreationElement - 
  class CreationElement : public state::IObservateurEtat {
    // Operations
  public:
    void Evenement ();
  };

};

#endif
