// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {

  /// class Element - 
  class Element {
    // Attributes
  protected:
    int x;
    int y;
    // Operations
  public:
    Element ();
    virtual ~Element ();
    virtual bool const estPersonnage () = 0;
    virtual int const getID () = 0;
    int const getX ();
    int const getY ();
    void setX (int x);
    void setY (int  y);
  };

};

#endif
