// Generated by dia2code
#ifndef ELEMENTALLOC__H
#define ELEMENTALLOC__H

/// class ElementAlloc - 
class ElementAlloc : public AElementAlloc {
  // Attributes
protected:
  ID id;
  // Operations
public:
  ElementAlloc (ID id);
  Element* newInstance ();
};

#endif
