// Generated by dia2code
#ifndef ELEMENT__H
#define ELEMENT__H

/// class Element - 
class Element {
  // Attributes
protected:
  int x;
  int y;
  // Operations
public:
  Element ();
  virtual ~Element ();
  virtual bool const estPersonnage () = 0;
  int const getX ();
  int const getY ();
  void setX (int x);
  void setY (int  y);
};

#endif
