// Generated by dia2code
#ifndef ETAT__H
#define ETAT__H

#include "ListeElement.h"
#include "GrilleElement.h"

/// class Etat - 
class Etat {
  // Associations
  // Attributes
protected:
  ListeElement liste;
  GrilleElement grille;
  // Operations
public:
  Etat ();
  ~Etat ();
  Etat* const clone ();
  void copy (const Etat& other);
  bool const equals (const Etat& other);
  GrilleElement getGrille ();
  ListeElement getListe ();
  void setGrille (const GrilleElement grille);
  void setListe (const ListeElement list);
};

#endif
