// Generated by dia2code
#ifndef STATE__EVENEMENTETAT__H
#define STATE__EVENEMENTETAT__H


namespace state {
  class Etat;
}

#include "TypeEvenementEtat.h"

namespace state {

  /// class EvenementEtat - 
  class EvenementEtat {
    // Associations
    // Attributes
  public:
    float zoom;
    int camerax;
    int cameray;
  private:
    TypeEvenementEtat id;
    Etat* etat;
    int x;
    int y;
    int pid;
    int newX;
    int newY;
    // Operations
  public:
    EvenementEtat (TypeEvenementEtat id, Etat* etat, int x, int y, int pid, bool equipe, int newX = -1, int newY = -1, float zoom = 1, int camerax = 0, int cameray = 0);
    TypeEvenementEtat getTypeEvenement ();
    int getX ();
    int getY ();
    int getPid ();
    int getNewx ();
    int getNewy ();
    float getZoom ();
    int getCamerax ();
    int getCameray ();
  };

};

#endif
