// Generated by dia2code
#ifndef STATE__GRILLEELEMENT__H
#define STATE__GRILLEELEMENT__H


namespace state {
  class Etat;
  class ListeElement;
}

#include "ListeElement.h"

namespace state {

  /// class GrilleElement - 
  class GrilleElement : public state::ListeElement {
    // Attributes
  protected:
    int hauteur;
    int largeur;
    // Operations
  public:
    GrilleElement (Etat& e);
    int const getHauteur ();
    int const getLargeur ();
    Element* const getCellulePersonnage (int i, int j);
    Element* const getCelluleDécor (int i, int j);
    void genererTerrainAleatoire ();
  };

};

#endif
