// Generated by dia2code
#ifndef STATE__GRILLEELEMENT__H
#define STATE__GRILLEELEMENT__H


namespace state {
  class Etat;
  class ListeElement;
  class Personnage;
  class CaseTerrain;
}

#include "ListeElement.h"
#include "Personnage.h"
#include "CaseTerrain.h"

namespace state {

  /// class GrilleElement - 
  class GrilleElement : public state::ListeElement {
    // Associations
    // Attributes
  protected:
    int hauteur;
    int largeur;
    // Operations
  public:
    GrilleElement (Etat* e);
    int const getHauteur ();
    int const getLargeur ();
    Personnage* const getCellulePersonnage (int i, int j);
    CaseTerrain* const getCelluleDecor (int i, int j);
    void genererTerrainAleatoire ();
  };

};

#endif
