// Generated by dia2code
#ifndef GRILLEELEMENT__H
#define GRILLEELEMENT__H

/// class GrilleElement - 
class GrilleElement : public ListeElement {
  // Attributes
protected:
  int hauteur;
  int largeur;
  // Operations
public:
  GrilleElement (Etat& e);
  int const getHauteur ();
  int const getLargeur ();
  Element* const getCellulePersonnage (int i, int j);
  Element* const getCelluleDécor (int i, int j);
};

#endif
