// Generated by dia2code
#ifndef STATE__IOBSERVATEURETAT__H
#define STATE__IOBSERVATEURETAT__H


namespace state {

  /// class IObservateurEtat - 
  class IObservateurEtat {
    // Operations
  public:
    virtual void Evenement () = 0;
  };

};

#endif
