// Generated by dia2code
#ifndef LISTEELEMENT__H
#define LISTEELEMENT__H

#include "Element.h"
#include <vector>

class Etat;

/// class ListeElement - 
class ListeElement {
  // Associations
  // Attributes
protected:
  Etat *e;
  std::vector<Element*> elements;
  // Operations
public:
  ListeElement ();
  ~ListeElement ();
  ListeElement* const clone ();
  void copy (const ListeElement& liste);
  bool const equals (const ListeElement& other);
  int const size ();
  Element* const get (int i);
  void clear ();
  void set (int i, Element* e);
  void add(Element*);
};

#endif
