// Generated by dia2code
#ifndef STATE__LISTEELEMENT__H
#define STATE__LISTEELEMENT__H

#include <vector>

namespace state {
  class Etat;
  class Element;
  class ListeElement;
  class Personnage;
}

#include "Element.h"

namespace state {

  /// class ListeElement - 
  class ListeElement {
    // Associations
    // Attributes
  protected:
    Etat& e;
    ElementFactory* factory;
    std::vector<Element*> elements;
    // Operations
  public:
    ListeElement (Etat& e);
    ~ListeElement ();
    ListeElement* const clone ();
    void copy (const ListeElement& list);
    bool const equals (const ListeElement& other);
    int const size ();
    Element* const get (int i);
    void clear ();
    void set (int i, Element* e);
    void add (Personnage* p);
  };

};

#endif
