// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H

#include <list>

namespace state {
  class Observateur;
  class EvenementEtat;
}

#include "Observateur.h"

namespace state {

  /// class Observable - 
  class Observable {
    // Associations
    // Attributes
  private:
    std::list<Observateur*> observateurs;
    // Operations
  public:
    void enregistrerObservateur (Observateur* );
    void avertirObservateurs (const EvenementEtat& e);
  };

};

#endif
