// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H

#include <list>

namespace state {
  class IObservateurEtat;
}

#include "IObservateurEtat.h"

namespace state {

  /// class Observable - 
  class Observable {
    // Associations
    // Attributes
  private:
    std::list<IObservateurEtat*> observateurs;
    // Operations
  public:
    void enregistrerObservateur (IObservateurEtat* );
    void avertirObservateurs ();
  };

};

#endif
