// Generated by dia2code
#ifndef PERSONNAGE__H
#define PERSONNAGE__H
#include "TypePersonnage.h"
#include "Element.h"

/// class Personnage - 
class Personnage : public Element {
  // Associations
  // Attributes
protected:
  int pv;
  int pa;
  bool orientation;
  int id;
  bool equipe;
  int pvMax;
  int paMax;
  int porteeMax;
  int porteeMin;
  int attaque;
  // Operations
public:
  Personnage (bool equipe, TypePersonnage type);
  virtual ~Personnage ();
  bool const estPersonnage ();
  int const getPV ();
  int getPA ();
  bool const getOrientation ();
  int const getID ();
  bool const getEquipe ();
  int const getPVMax ();
  int const getPAMax ();
  void setPVrestant (int pv);
  void setPArestant (int pa);
  bool const equals ( const Personnage);
  void clone ( Element* const);
  int const getPorteeMax ();
  int const getPorteeMin ();
  int const getAttaque ();
  TypePersonnage getType ();
};

#endif
