// Generated by dia2code
#ifndef STATE__PERSONNAGE__H
#define STATE__PERSONNAGE__H


namespace state {
  class Personnage;
  class Element;
}

#include "TypePersonnage.h"
#include "Element.h"

namespace state {

  /// class Personnage - 
  class Personnage : public state::Element {
    // Associations
    // Attributes
  protected:
    int pv;
    int pa;
    bool orientation;
    int id;
    bool equipe;
    int pvMax;
    int paMax;
    int porteeMax;
    int porteeMin;
    int attaque;
    // Operations
  public:
    Personnage (bool equipe, TypePersonnage type);
    virtual ~Personnage ();
    bool const estPersonnage ();
    int const getPV ();
    int getPA ();
    bool const getOrientation ();
    int const getID ();
    bool const getEquipe ();
    int const getPVMax ();
    int const getPAMax ();
    void setPVrestant (int pv);
    void setPArestant (int pa);
    bool const equals (const Personnage& p);
    Personnage* clone ();
    int const getPorteeMax ();
    int const getPorteeMin ();
    int const getAttaque ();
    TypePersonnage getType ();
  };

};

#endif
