// Generated by dia2code
#ifndef STATE__TYPEPERSONNAGE__H
#define STATE__TYPEPERSONNAGE__H


namespace state {

  enum TypePersonnage {
    Spadassin     = 1,
    Lancier     = 2,
    Archer     = 3,
    Canon     = 4,
    Cavalier     = 5,
    Roi     = 6
  };

};

#endif
