// Generated by dia2code
#ifndef STATE__TYPEEVENEMENTETAT__H
#define STATE__TYPEEVENEMENTETAT__H


namespace state {

  enum TypeEvenementEtat {
    PersonnageDeplace     = 1,
    PersonnageMort     = 2,
    NouveauPersonnage     = 3,
    NouveauDecor     = 4,
    DeplacementCamera     = 5,
    ZoomCamera     = 6,
    ModeDeplacement     = 7,
    ChangementSelectionne     = 8,
    ModeAttaque     = 9
  };

};

#endif
