// Generated by dia2code
#ifndef CASETERRAIN__H
#define CASETERRAIN__H

/// class CaseTerrain - 
class CaseTerrain : public Element {
  // Associations
  // Attributes
private:
  int id;
  std::vector<Acces> liste_acces;
  int hauteur;
  // Operations
public:
  CaseTerrain (int id = 0);
  bool const estPersonnage ();
};

#endif
