// Generated by dia2code
#ifndef __COUCHE__H
#define __COUCHE__H

#include <vector>

namespace  {
  class Tuile;
}

#include "Tuile.h"

namespace  {

  /// class Couche - 
  class Couche {
    // Associations
    // Attributes
  public:
    std::vector<Tuile*> tuiles;
    // Operations
  public:
    Couche ();
    Tuile* getTuile (int i, int j);
    void setTuile (int i, int j, Tuile* tuile);
  };

};

#endif
