// Generated by dia2code
#ifndef ELEMENTFACTORY__H
#define ELEMENTFACTORY__H

/// class ElementFactory - 
class ElementFactory {
  // Associations
  // Attributes
protected:
  std::map<char ,AElementAlloc*> list;
  // Operations
public:
  ~ElementFactory ();
  Element* const newInstance (char id);
  void registerType (char id, AElementAlloc* a);
};

#endif
