// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/Action.h"
#include "engine/Attaquer.h"
#include "engine/Deplacement.h"
#include "engine/Zoom.h"
#include "engine/DeplacementCamera.h"
#include "engine/Selection.h"
#include "engine/ChangerMode.h"
#include "engine/ListeActions.h"
#include "engine/Regulateur.h"
#include "engine/CategorieCommande.h"
#include "engine/Commande.h"
#include "engine/CommandeZoomCamera.h"
#include "engine/Direction.h"
#include "engine/CommandeFleche.h"
#include "engine/CommandeClic.h"
#include "engine/CommandeEchap.h"
#include "engine/ListeCommande.h"
#include "engine/Mode.h"
#include "engine/Moteur.h"
#include "engine/Historique.h"
#include "engine/ChangerTour.h"
#include "engine/PlacementTroupe.h"
#include "engine/ChangerInit.h"
#endif
