// Generated by dia2code
#ifndef __RENDER__H
#define __RENDER__H

#include "render/Tuile.h"
#include "render/TuileStatique.h"
#include "render/TuileAnimee.h"
#include "render/Couche.h"
#include "render/Scene.h"
#endif
