// Generated by dia2code
#ifndef __SCENE__H
#define __SCENE__H


namespace  {
  class Couche;
}

#include "Couche.h"

namespace  {

  /// class Scene - 
  class Scene {
    // Associations
    // Attributes
  public:
    couchePersonnage Couche*;
    coucheTerrain Couche*;
    etat Etat*;
    // Operations
  public:
    Scene (Etat* etat);
  };

};

#endif
