// Generated by dia2code
#ifndef __TUILEANIMEE__H
#define __TUILEANIMEE__H

#include <stdint.h>
#include <vector>

namespace  {
  class Tuile;
}

#include "Tuile.h"

namespace  {

  /// class TuileAnimee - 
  class TuileAnimee : public ::Tuile {
    // Attributes
  public:
    int64_t debut;
  private:
    std::vector<const Tiles*> tuiles;
    float pourcentage;
    float vitesse;
    // Operations
  public:
    TuileAnimee (int id, float rate);
    ~TuileAnimee ();
    bool estAnime ();
    const float getPourcentage ();
    void setPourcentage (rate float);
    Tile* getTuile (int i);
    void setVItesse (float speed);
    const float getVitesse ();
    void ajouterTuile (Tile* tile);
    void setTuile (int i, Tile* tile);
    void update (int64_t time);
    sync (temps int64_t);
  };

};

#endif
