// Generated by dia2code
#ifndef __TUILESTATIQUE__H
#define __TUILESTATIQUE__H


namespace  {
  class Tuile;
}

#include "Tuile.h"

namespace  {

  /// class TuileStatique - 
  class TuileStatique : public ::Tuile {
    // Attributes
  private:
    int hauteur;
    int largeur;
    sf::Texture texture;
    sf::Sprite sprite;
    // Operations
  public:
    TuileStatique (int id);
    ~TuileStatique ();
    int const getHauteur ();
    int const getLargeur ();
    void setHauteur (int hauteur);
    void setLargeur (int largeur);
    const sf::Sprite& getSprite ();
    bool estAnime ();
  };

};

#endif
