// Generated by dia2code
#ifndef TYPEPERSONNAGE__H
#define TYPEPERSONNAGE__H

enum TypePersonnage {
  Spadassin   = 1,
  Lancier   = 2,
  Archer   = 3,
  Canon   = 4,
  Cavalier   = 5,
  Roi   = 6
};

#endif
